coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 1%

ignore:
  - "client/**/*"
  - "**/*_test.go"
  - "**/mock/**"
  - "**/mocks/**" 